name: Bun Tests
on:
  push:
    branches: [main, master, stable]
  pull_request:
    branches: [main, master, stable]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build app
        run: bun test unit --coverage
